### PR TITLE
updated stanford_soe_helper

### PR DESCRIPTION
**Pull request by boznik**
# READY FOR REVIEW

# Summary
- Updated twitter card

# Review Needed By (Date)
- Soonish

# Urgency
- mild

# Steps to Test

1. Verify the tagged version of stanford_soe_helper is on the latest release in the stanford.make file: https://github.com/SU-SOE/stanford_soe_helper/releases

# Affected Projects or Products
- SOE main site

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOEOP-256

### CODE REVIEW

**Review by imonroe — APPROVED** [review]
Pretty straightforward.

**Comment by imonroe** [comment]
Apparently I can't merge this though: 
image

**Comment by sherakama** [comment]
> Apparently I can't merge this though:

@imonroe How bout now?

**Comment by imonroe** [comment]
> > Apparently I can't merge this though:
> 
> @imonroe How bout now?

Perfecto.  Thanks, sir.

**Pull request merged**
