### PR TITLE
SOE-XXX - removed engineering homepage behat test.

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- Removed brittle behat test. (Test no longer relevant to layout being used on production.)

# Review By (Date)
12/1

# Criticality
0/10

### CODE REVIEW

**Comment by boznik** [comment]
Is there a test that checks just to make sure the homepage is existential? maybe this could be gutted for the brittle bean counts and just used to make sure the homepage loads? if that gets tested elsewhere, i think it's fine to drop it entirely.

**Comment by mdyoung3** [comment]
@boznik It's more existential than Albert Camus novel. ;) 

I did a cursory search and found a couple of tests to check for things like region and menu links from the homepage. Would that qualify?

**Comment by boznik** [comment]
Good by me, get rid of this thing...

**Comment by mdyoung3** [comment]
Would you like me to do the honors?

**Comment by boznik** [comment]
Aha, i have been under the assumption that whomever is assigned the PR pulls the trigger.

**Review by boznik — APPROVED** [review]
GTG

**Pull request merged**
