### PR TITLE
SOEOP-000 - Some Docksal config updates

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
Some tweaks to the Docksal configuration. 
- 

# Review By (Date)
6/8

# Criticality
- 1/10

# Review Tasks

## Setup tasks and/or behavior to test

1. clone site and run `fin init`

### CODE REVIEW

**Comment by jbickar** [comment]
Looking at this today. Sorry for the delay.

**Comment by jbickar** [comment]
Am I supposed to run `fin test` to verify the new command?

**Comment by jbickar** [comment]
```
spr-jbickar-9: ~/Documents/working/ACE/grunt-drupal-tasks$ fin test
Testing home page...
HTTP/1.1 200 OK
```

**Review by jbickar — APPROVED** [review]
LGTM. Sorry for the delay.

**Comment by mdyoung3** [comment]
Test not necessary, but nice. 👍

**Comment by jbickar** [comment]
@sherakama, see - I *do* sometimes review pull requests.

**Pull request merged**
