### PR TITLE
SOEOP-402 - Adding latest Alpha version of Stanford SSP to engineering.make.

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- The original issue was a session cookie being init twice in two modules, thus creating a PHP warning. This PR contains a conditional to check for 

# Review By (Date)
01/18

# Criticality
- 5/10

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Run grunt init
3. Run grunt behat test
4. Review site, and check the logs for the ini_set() warning after clearing the logs in the watchdog (you may have to enable to the Database Loggin admin).

# Associated Issues and/or People
- https://stanfordits.atlassian.net/jira/software/c/projects/SOEOP/issues/SOEOP-402

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by mdyoung3** [comment]
@jbickar @sherakama and @boznik 

Behat fails on on the [diversity page on SOE tests](https://engineering.stanford.edu/students-academics/equity-and-inclusion-initiatives).  

I checked the test results against the page as it stands on production. And it would fail on production too. 

I did a cursory search in Jira for tickets for the diversity page and couldn't see anything related. Probably a database change or content change? It didn't fail recently. 

Is there anything to be done or are the tests wrong? 

Behat test: 
[diversity-page--failed.txt](https://github.com/SU-SOE/grunt-drupal-tasks/files/5804358/diversity-page--failed.txt)

**Comment by sherakama** [comment]
Yeah, It looks like the failing tests are not related to this PR. I would either update or remove the failing behat test scenarios.

**Comment by mdyoung3** [comment]
@sherakama @jbickar and @boznik 

Does anyone know why the engineering.make file pointed to `7.x-2.2-alpha7` instead of `7.x-2.2-alpha10`?

**Comment by sherakama** [comment]
According to the blame/history of that file it has been that way for the last two years.
https://github.com/SU-SOE/grunt-drupal-tasks/blame/8757dfb0df92c116c116bf882847e201aea4dc0d/soe/src/stanford.make#L271

Guess it wasn't updated after being ported to this build system.

**Comment by jbickar** [comment]
Based on memory, I believe that the upgrade path from `alpha7` to `alpha10` is clean, so I would go ahead and upgrade it to the latest in the make file.

**Comment by jbickar** [comment]
https://github.com/SU-SWS/stanford_ssp/compare/7.x-2.2-alpha7...7.x-2.2-alpha11

**Comment by mdyoung3** [comment]
Okay, with that said, I updated the test and it passed. 

@sherakama and/or @boznik  Please one of you review this?

**Review by sherakama — APPROVED** [review]
Yeah, this is fine.

**Pull request merged**
