### PR TITLE
SOEOP-252: Document and backup SOLR config

### PR DESCRIPTION
**Pull request by boznik**
# READY FOR REVIEW

# Summary
- Added backup of Solr config file.

# Review By (Date)
- Soon

# Urgency
- low

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Verify there is a backup of schema.xml in soe/docs directory
3. Review build notes addition

### CODE REVIEW

**Review by jbickar — CHANGES_REQUESTED** [review]
Please add the documentation from https://asconfluence.stanford.edu/confluence/display/SWS/SOE+Solr+Documentation

**Comment by jbickar** [comment]
Changes requested. Bouncing to @sherakama and @pookmish for review while I'm out.

**Comment by sherakama** [comment]
Please add the documentation from asconfluence.stanford.edu/confluence/display/SWS/SOE+Solr+Documentation

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
