### PR TITLE
updated core to 7.71

### PR DESCRIPTION
**Pull request by boznik**
# READY FOR REVIEW

# Summary
- Updating core to 7.71

# Review By (Date)
- 6/15/2020

# Urgency
- low

# Review Tasks

## Setup tasks and/or behavior to test

1. Verify that build used drupal core 7.71. build available for review on https://eng-stage.stanford.edu

# Affected Projects or Products
- SOE main site

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOEOP-284
- Fixes bug with chrome and image upload

### CODE REVIEW

**Comment by jbickar** [comment]
@boznik, is this work already pushed to SoE prod? I'm seeing 7.71 there.

**Comment by boznik** [comment]
yes, this has been the process on soe. behat tests were run on the artifact and internal and client review happened on dev/stage along with amp testing.

**Comment by boznik** [comment]
ping...ping...ping

**Review by imonroe — APPROVED** [review]
No problem with me, especially since it's already on prod.

**Pull request merged**
