### PR TITLE
SOEOP-350: Update for PHP 7.3 compatibility

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

Please build and deploy and I can push it to Acquia

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
Ok

**Comment by jbickar** [comment]
When I try to package this, it does not pick up the changes. E.g.,:

```
spr-jbickar-9: ~/Documents/working/ACE/grunt-drupal-tasks/soe$ touch src/engineering.make  && grunt package && grep version build/packages/package/docroot/sites/all/modules/contrib/date/date.info
Running "notify_hooks" task

Running "package" task

Running "clean:packages" (clean) task
>> 1 path cleaned.
Created 2312 directories, copied 12381 files

Done.
version = "7.x-2.9"
```

**Comment by jbickar** [comment]
@sherakama , are you able to get the packaging to work with this branch? I am keeping @imonroe busy with CAW PHP 7.3 changes.

**Comment by sherakama** [comment]
I can give it a whirl.

**Comment by sherakama** [comment]
@jbickar 

- Build was created and branch `drupal-7.73` was pushed to https://github.com/su-sws/sws_soe_ace
- Tag was created from build branch `0.0.27`
- Diff from previous version https://github.com/SU-SWS/sws_soe_ace/compare/0.0.26...0.0.27
- 0.0.27 was deployed to https://eng-dev.stanford.edu/

**Comment by jbickar** [comment]
@sherakama , thank you, I will review.

**Comment by sherakama** [comment]
Approved when client approves.

**Pull request merged**
