### PR TITLE
SOEOP-366 - added new version of stanford helper module with latest c…

### PR DESCRIPTION
**Pull request by mdyoung3**
# READY FOR REVIEW

# Summary
- Client requests for changes to banner.

# Review By (Date)
- 10/12

# Criticality
- 8/10.
- Production site

# Review Tasks

## Setup tasks and/or behavior to test

1. Clone repo locally or pull latest
2. Run `grunt` to pull in new module.
3. Check any one of the news page for a banner like this. 

Screen Shot 2020-12-09 at 7 29 09 PM

# Associated Issues and/or People
- https://stanfordits.atlassian.net/jira/software/c/projects/SOEOP/issues/SOEOP-366

### CODE REVIEW

**Comment by boznik** [comment]
Running fresh build.

**Comment by boznik** [comment]
I found 2 failed behat scenarios:

--- Failed scenarios:

features/drupal.org/context/context.feature:7

1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
0m9.74s (43.88Mb)

>> Failed: ./test/features/drupal.org/context/context.feature - 1 scenario (1 failed) in 0m9.74s (43.88Mb)

--

    features/engineering_stanford_bean_types/stanford_bean_types_banner.feature:24

8 scenarios (7 passed, 1 failed)
47 steps (40 passed, 1 failed, 6 skipped)
1m0.06s (46.12Mb)

>> Failed: ./test/features/engineering_stanford_bean_types/stanford_bean_types_banner.feature - 8 scenarios (7 passed, 1 failed) in 1m0.06s (46.12Mb)

**Review by sherakama — APPROVED** [review]
Code looks fine. I will leave it to the two of you to sort out the behat issue. @boznik can you also provide the parts of the behat run where it outputs what went wrong and not just the line numbers. Thanks.

**Comment by mdyoung3** [comment]
@boznik Let me run those on my local and see if I can replicate. (I ran this through behat on mine and I don't think it had any fails.)

**Comment by boznik** [comment]
sounds good. i'll double check as well, as i've had some issues bouncing between docker and my other local dev.

**Comment by mdyoung3** [comment]
@boznik Sometimes I get false positives because MySQL locks. 

I just ran it again and got a different failure from yours. (Wasn't in debugging mode, so I'm not sure why.)

**Comment by mdyoung3** [comment]
@boznik Ran it again on with `debug: true` and didn't run into issues this time. As I mentioned, I suspect sometimes MySQL might have gotten locked with the database getting too many queries in a short period of time. ¯\_(ツ)_/¯

**Comment by boznik** [comment]
@mdyoung3 yes, the errors were due to a deadlock. this is GTG

**Review by boznik — APPROVED** [review]
GTG

**Pull request merged**
